version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: mern-frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Map container port 80 to host port 3000
    depends_on:
      - api
    networks:
      - mern-network

  # Backend API service
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mern-api
    restart: unless-stopped
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mern-deployment
    depends_on:
      - mongo
    networks:
      - mern-network

  # MongoDB service
  mongo:
    image: mongo:5.0
    container_name: mern-mongo
    restart: unless-stopped
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: mern-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090" # Map container port 9090 to host port 9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - mern-network

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:9.3.6
    container_name: mern-grafana
    restart: unless-stopped
    ports:
      - "3001:3000" # Map container port 3000 to host port 3001
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - mern-network

  # Node exporter for host metrics
  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: mern-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - "9100:9100"
    networks:
      - mern-network

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  mern-network:
    driver: bridge